name: CI Build Pipeline
on:
    pull_request:
        branches: [ develop, main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - run: yarn --ci
            - run: yarn test
